version: '3.8'
services:
  movies:
    image: parashuram9/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  recharge:
    image: parashuram9/payrecharge:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3


